name: maugost_apps
description: Find your soul mate

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_maps_flutter: ^0.5.27+3
  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+4
  image_cropper: ^1.2.1
  connectivity: ^0.4.6+1
  pull_to_refresh: 1.5.8
  device_id: ^0.2.0
  cached_network_image: ^2.0.0
  timeago: ^2.0.22
#  photo_manager: 0.4.8
  photo: ^0.5.0-dev.3
  photo_manager: 0.5.2
  permission_handler: ^5.0.0+hotfix.3
  package_info: ^0.4.0+16
  ntp: ^1.0.4
  photo_view: 0.9.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_spinkit: ^4.1.1+1
  flutter_simple_video_player: 0.0.9
  uuid: 2.0.0
  path: any

  flutter_keyboard_visibility: ^2.0.0
  keyboard_dismisser: ^1.0.2
  emoji_picker: 0.1.0
  loading_indicator: ^1.1.0
  filesize: ^1.0.4
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.15
  firebase_analytics: ^5.0.11
  flutter_linkify: ^2.1.0
  audioplayers: ^0.15.1
  vibration: ^1.2.2
  dashed_circle: ^0.0.1
  datetime_picker_formfield: ^0.4.3
  shared_preferences: ^0.5.6+3

  intl: ^0.16.0
  url_launcher: 5.4.2

  cloud_functions: ^0.5.0
  money_field: ^1.0.1
  synchronized: ^2.2.0
  device_info: ^0.4.2+1
  provider: ^4.0.5
#  camera: ^0.5.8+1
  rect_getter: ^0.0.1
  video_player: 0.10.5+2
  google_fonts:
  sign_in_with_apple: ^2.3.0
  google_sign_in: ^4.5.1
  flutter_login_facebook: ^0.2.0+1
  shimmer: ^1.1.1
  flutter_keyboard_size: ^0.1.2+2
  flutter_sound: ^4.0.0
  flutter_xlider: ^3.3.0
  scrollable_positioned_list: ^0.1.5

  flutter_icons: ^1.1.0
  random_color: ^1.0.5
  masked_controller: ^1.0.1
  flutter_masked_text:
  font_awesome_flutter:

  currency_pickers: ^1.0.6
  stripe_payment: ^1.0.7

  awesome_card: ^1.1.0
  virtual_keyboard: ^0.1.4

  line_icons: ^0.2.0
  devicelocale: ^0.3.1
  multipart_request: ^0.3.1
  stripe_sdk: ^3.0.1+1
  latlong:
  geolocator: 5.3.2
  flare_flutter: ^2.0.6
  country_pickers: ^1.1.0


dependency_overrides:
  uuid: ^2.0.4
  intl: ^0.15.8
  geoflutterfire: ^2.1.0
  location: ^3.0.2
  camera:
    git:
      url: git://github.com/mtellect/flutter_camera_flash


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
       - family: GlamIcons
         fonts:
           - asset: assets/fonts/GlamIcons.ttf
       - family: Averta
         fonts:
           - asset: assets/fonts/Averta.otf

       - family: AvertaB
         fonts:
           - asset: assets/fonts/AvertaB.ttf
            #  weight: 700


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/
    - flags/


    